import re

from pydantic import BaseModel, field_validator, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum

# Enum for order status, with values matching our class diagram.
class OrderStatus(str, Enum):
    UNPAID = "unpaid"
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    READY_FOR_PICKUP = "ready_for_pickup"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

# Base schema for OrderItem, containing all fields.
class OrderItem(BaseModel):
    menu_item_id: int
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)
    price_at_time: float

# Schema for creating an OrderItem, excluding the price which will be calculated based on the menu item.
class OrderItemCreate(BaseModel):
    menu_item_id: int
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)

# Schema for updating an OrderItem, allowing only the quantity to be updated.
class OrderItemUpdate(BaseModel):
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)

# Base schema for Order, containing all fields.
class Order(BaseModel):
    id: str                     # Generated by OrderService
    customer_id: str
    restaurant_id: int
    items: List[OrderItem]
    status: OrderStatus         # Generated by OrderService (starts as "unpaid")
    order_date: datetime        # Generated by OrderService
    cost_breakdown: float       # TODO: Replace with CostBreakdown when definied
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

# Schema for creating an Order, excluding fields that are marked as generated by OrderService.
class OrderCreate(BaseModel):
    customer_id: str
    restaurant_id: int
    items: List[OrderItemCreate]
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

# Schema for updating an Order. Allows modification of everything from OrderCreate except id's or items. Also allows updating status.
class OrderUpdate(BaseModel):
    status: Optional[OrderStatus] = None
    delivery_address: Optional[str] = None
    delivery_latitude: Optional[float] = None
    delivery_longitude: Optional[float] = None
    delivery_postal_code: Optional[str] = None
    delivery_instructions: Optional[str] = None