from uuid import UUID, uuid4

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum

class OrderStatus(str, Enum):
    UNPAID = "unpaid"
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    READY_FOR_PICKUP = "ready_for_pickup"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

class Order(BaseModel):
    id: str                     # Generated by OrderService
    customer_id: str
    restaurant_id: int
    items: List[OrderItem]
    status: OrderStatus         # Generated by OrderService (starts as "unpaid")
    order_date: datetime        # Generated by OrderService
    cost_breakdown: float       # TODO: Replace with CostBreakdown when definied
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

class OrderCreate(BaseModel):
    customer_id: str
    restaurant_id: int
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

class OrderUpdate(BaseModel):
    status: Optional[OrderStatus] = None
    delivery_address: Optional[str] = None
    delivery_latitude: Optional[float] = None
    delivery_longitude: Optional[float] = None
    delivery_postal_code: Optional[str] = None
    delivery_instructions: Optional[str] = None
=========
# backend/schemas/order_schema.py
from pydantic import BaseModel, ConfigDict
from enum import Enum

# This is a dummy file to allow for review service to be tested

class OrderStatus(str, Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

class Order(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    status: OrderStatus
    restaurant_id: int
    customer_id: str
>>>>>>>>> Temporary merge branch 2
