import re

from pydantic import BaseModel, field_validator, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum

# Enum for order status, with values matching our class diagram.
class OrderStatus(str, Enum):
    UNPAID = "unpaid"
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    READY_FOR_PICKUP = "ready_for_pickup"
    COMPLETED = "completed"
    CANCELLED = "cancelled"

# Base schema for OrderItem, containing all fields.
class OrderItem(BaseModel):
    menu_item_id: int
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)
    price_at_time: float

# Schema for creating an OrderItem, excluding the price which will be calculated based on the menu item.
class OrderItemCreate(BaseModel):
    menu_item_id: int
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)

# Schema for updating an OrderItem, allowing only the quantity to be updated.
class OrderItemUpdate(BaseModel):
    quantity: int = Field(gt = 0) # Checks that quantity is greater than 0 (built in Pydantic validator shortcut)

# Base schema for Order, containing all fields.
class Order(BaseModel):
    id: int                     # Generated by OrderService
    customer_id: str
    restaurant_id: int
    items: List[OrderItem]
    status: OrderStatus         # Generated by OrderService (starts as "unpaid")
    order_date: datetime        # Generated by OrderService
    subtotal: float             # Generated by OrderService TODO: Feat7
    delivery_fee: float         # Generated by OrderService TODO: Feat7
    tax_gst: float              # Generated by OrderService TODO: Feat7
    tax_pst: float              # Generated by OrderService TODO: Feat7
    total_price: float          # Generated by OrderService TODO: Feat7
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

# Schema for creating an Order, excluding fields that are marked as generated by OrderService.
class OrderCreate(BaseModel):
    customer_id: str
    restaurant_id: int
    items: List[OrderItemCreate]
    delivery_address: Optional[str] = None
    delivery_latitude: float
    delivery_longitude: float
    delivery_postal_code: str
    delivery_instructions: Optional[str] = None

    # -- Validator methods --
    @field_validator('delivery_postal_code')
    @classmethod
    def validate_delivery_postal_code(cls, value: str) -> str:
        regex_pattern = r"^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$"
        # This says that postal code must be, letter, number, letter, space/hyphen (optional), number, letter, number.
        # To enforce simplicity, we aren't including the rule that the first letter can't be D, F, I, O, Q, or U.

        if not re.match(regex_pattern, value):
            # If it fails, FastAPI will automatically catch this as a ValueError 
            raise ValueError("Must be a valid Canadian postal code (e.g., V1V 1V1)")
        return value

    @field_validator('delivery_latitude')
    @classmethod
    def validate_delivery_latitude(cls, value: float) -> float:
        if value < -90 or value > 90:
            raise ValueError("Latitude must be between -90 and 90")
        return value

    @field_validator('delivery_longitude')
    @classmethod
    def validate_delivery_longitude(cls, value: float) -> float:
        if value < -180 or value > 180:
            raise ValueError("Longitude must be between -180 and 180")
        return value

# Schema for updating an Order. Allows modification of everything from OrderCreate except id's or items. Also allows updating status.
class OrderUpdate(BaseModel):
    status: Optional[OrderStatus] = None
    delivery_address: Optional[str] = None
    delivery_latitude: Optional[float] = None
    delivery_longitude: Optional[float] = None
    delivery_postal_code: Optional[str] = None
    delivery_instructions: Optional[str] = None

    # -- Validator methods --
    @field_validator('delivery_postal_code')
    @classmethod
    def validate_delivery_postal_code(cls, value: str) -> Optional[str]:
        if value is None:
            return value # Skip validation if they aren't trying to update it
        
        regex_pattern = r"^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$"
        # This says that postal code must be, letter, number, letter, space/hyphen (optional), number, letter, number.
        # To enforce simplicity, we aren't including the rule that the first letter can't be D, F, I, O, Q, or U.
 
        if not re.match(regex_pattern, value):
            # If it fails, FastAPI will automatically catch this as a ValueError 
            raise ValueError("Must be a valid Canadian postal code (e.g., V1V 1V1)")
        return value

    @field_validator('delivery_latitude')
    @classmethod
    def validate_delivery_latitude(cls, value: float) -> Optional[float]:
        if value is None:
            return value # Skip validation if they aren't trying to update it
        
        if value < -90 or value > 90:
            raise ValueError("Latitude must be between -90 and 90")
        return value

    @field_validator('delivery_longitude')
    @classmethod
    def validate_delivery_longitude(cls, value: float) -> Optional[float]:
        if value is None:
            return value # Skip validation if they aren't trying to update it
        
        if value < -180 or value > 180:
            raise ValueError("Longitude must be between -180 and 180")
        return value
