name: Move to In Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  move_to_review:
    runs-on: ubuntu-latest
    steps:
      - name: Move project item to In Review
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.PROJECT_PAT }}
          user: ${{ github.repository_owner }}
          project_id: 1 
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "In review"
